version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: compliments_db
    restart: always
    ports:
     - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tcompliments_db
    volumes:
     - pgdata:/data/postgres
  app:
    build: .
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    links: 
      - database_ignite
    depends_on:
      - database_ignite

volumes: 
  pgdata:
    driver: local